version: '2'
services:
  proxy:
    build: ./proxy
    links:
      - bbm-web
      - bookmark
      - recommendation
    ports:
      - 80:80
      - 443:443
  bbm-web:
    build: ./bbm-web
    expose:
      - "80"
  bookmark:
    build: ./bookmark/source
    expose:
      - "80"
    depends_on:
      - rabbitmq
      - bookmark-db
    links:
      - rabbitmq
      - bookmark-db
  bookmark-db:
    image: mongo
    ports:
      - 28001:27017
  recommendation:
    build: ./recommendation/source
    expose:
      - "80"
    depends_on:
      - rabbitmq
      - recommendation-db
    links:
      - rabbitmq
      - recommendation-db
  recommendation-db:
    image: mongo
    ports:
      - 28002:27017
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"