version: '2'
services:
  proxy:
    build: ./proxy
    links:
      - bbm-auth-gateway
    ports:
      - 80:80
      - 443:443
  bbm-web:
    build: ./bbm-web
    ports:
      - "3000:3000"
    links:
      - "bbm-auth-gateway"
  bbm-auth-gateway:
    build: ./bbm-auth-gateway/source
    ports:
      - 8002:8002
    depends_on:
      - auth-db
    links:
      - bookmark
      - recommendation
  auth-db:
    image: mongo
    ports:
      - 28003:27017
  bookmark:
    build: ./bookmark/source
    ports:
      - "3100:3100"
    depends_on:
      - rabbitmq
      - bookmark-db
    links:
      - rabbitmq
      - bookmark-db
  bookmark-db:
    image: mongo
    ports:
      - 28001:27017
  recommendation:
    build: ./recommendation/source
    ports:
      - "3200:3200"
    depends_on:
      - rabbitmq
      - recommendation-db
    links:
      - rabbitmq
      - recommendation-db
  recommendation-db:
    image: mongo
    ports:
      - 28002:27017
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"